### PR TITLE
Add warning regarding feature set, link to features and plugin compat pages

### PR DESCRIPTION
**Pull request by dequis**
Also sneak in a tiny formatting fix because why not

Screenshot:

warning screenshot

Text:

> Glowstone is still in heavy development!
> 
> A lot of vanilla features are not implemented yet. There are no mobs, no redstone, no physics, but there are enough features for creative servers.
> 
> Additionally, some bukkit plugins may not work out of the box.
> 
> See the features and plugin compatibility pages for more details.

Navbar:

navbar screenshot

### CODE REVIEW

**Comment by dequis** [comment]
As suggested on irc, used some cheap font enlargement pills:



Looks much sexier now.

**Comment by turt2live** [comment]
@dequis If your font lasts more than 4 hours, seek medical attention.

**Comment by choyiny** [comment]
Honestly there isn't a need for that many warnings saying its in development process. Just put it in the title.

**Comment by turt2live** [comment]
@hkminegod There is a need. Just sit in `#glowstone` on IRC to find out why. Within 24 hours you'll realize that people aren't reading the existing warnings or version numbers.

**Comment by choyiny** [comment]
That's why I suggest putting "In Development" in the subtitle:

The in development lightweight Minecraft server.

**Comment by turt2live** [comment]
That still won't get people's attention. A giant box that says "IT'S NOT DONE" is more suitable, I believe.

**Comment by dequis** [comment]
also why isn't this merged yet, @SpaceManiac pls

**Comment by dequis** [comment]
guys srsly pls

**Comment by SpaceManiac** [comment]
Not yet sure if it's satisfactory, but merged in 52d234b. I decided to put the links in the warning rather than in the header to avoid adding even more links to the already-huge list.

**Comment by dequis** [comment]
I was avoiding that because that blue on orange looks... kinda bad. But main priority was having the message up there, making it nice doesn't matter as much. Thanks!

**Pull request closed without merging**
