### PR TITLE
Redesign website yet again

### PR DESCRIPTION
**Pull request by mastercoms**
Although our current website is good, I think it is utilitarian and needs a redesign.
You can see a preview here: https://glowstone-ghpages-c9-circuitsoft.c9.io/

### CODE REVIEW

**Comment by SpaceManiac** [comment]
On the whole, I like it. Looks really good. A few initial nitpicks:
- That front page is _really_ yellow. Some of the text is hard to read.
- The "Why" and "About" sections feel sort of bottom-aligned on a big screen.
- It's hard to notice that there's a thanks section if you follow only the header links.

**Comment by mastercoms** [comment]
I made the background easier on the eyes, and I added thanks to the navbar, and centered the sections.

**Comment by mastercoms** [comment]
The server was down, it is now back up for previewing. Sorry about that! 
I haven't committed the changes yet because I want the changes to be approved before I commit them.

**Comment by choyiny** [comment]
Dang, I've been doing the same... Still heavily under construction though.

btw can't open your preview mastercoms :/

**Comment by mastercoms** [comment]
@hkminegod Should be running again now.

**Comment by mastercoms** [comment]
Going to put this on my own server after I solve the merge conflicts.

**Pull request closed without merging**
