### PR TITLE
Add warning to downloads page

### PR DESCRIPTION
**Pull request by turt2live**
People keep expecting Glowstone to work for production environments. This is not true (yet!)

Images of the error (cause I'm too damn lazy to expose the server port):
- [Chrome](http://i.turt2live.com/w94N.png)
- [Firefox](http://i.turt2live.com/wBRX.png)
- [IE11](http://i.turt2live.com/0i5P.png)

And for those too lazy to click a link:
image

Edit: Here's a live preview: http://home.turt2live.com:4000

### CODE REVIEW

**Comment by gdude2002** [comment]
I approve of this message

**Comment by bendem** [comment]
:+1: for the message
:-1: for the `<b></b>`

**Comment by turt2live** [comment]
I was lazy, okay. It's a temporary message anyways.

**Comment by ghost** [comment]
@gdude2002 +1

**Comment by Tonodus** [comment]
I'm totally for this :+1:

**Comment by turt2live** [comment]
@bendem replaced with `<strong>`

**Comment by bendem** [comment]
:+1: for the message
:+1: for the `<string></string>`

**Comment by turt2live** [comment]
(added live preview link)

**Comment by gdude2002** [comment]
Can we merge this yet? .__.

**Comment by SpaceManiac** [comment]
Merged with a tweak in 3b23293a2aa4fa50f057990605c0339f794bb2de.

http://www.glowstone.net/downloads/

**Comment by turt2live** [comment]
HOW DARE YOU IMPROVE MY WORK.

(sweet)

**Pull request closed without merging**
